"""
make_test_vectors.py -- writes test_vectors.h for the buoy_esp32 boot self-test
================================================================================
Two checks, both from REAL rows of the Narragansett fork's data/narragansett_daily_features.csv:

1. Model check (TV_*): 8 station-day feature vectors (NaN kept as NAN) and the probability that
   Python gives for them, computed exactly as src/deploy/export_c_model.py does:
       pack["model"].predict_proba(DataFrame(X).fillna(Series(pack["medians"])).values)[:, 1]
   Rows are picked to cover: clear alerts, clear non-alerts, rows near the 0.45 threshold, and
   rows with missing DO / salinity / climatology (so the on-chip median fill is exercised).

2. Feature-engine check (HT_*): 29 consecutive daily rows of one station (date, chl, temp, sal,
   do, chl_climatology) and the fork's precomputed 23 features for the last 8 of them. The sketch
   feeds the 29 rows through its own rolling-history code and compares.

Run (LIS repo root or anywhere), BASE env:
    ~/anaconda3/python.exe hardware/buoy_esp32/make_test_vectors.py [--fork PATH]
Rerun it whenever release/bloom_model.h is regenerated in the fork.
"""
import argparse
import os

import joblib
import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_FORK = os.path.normpath(os.path.join(HERE, "..", "..", "..", "hab-bloom-predictor-narragansett"))
N_HIST, N_HIST_CHECK = 29, 8
HIST_STATION = "B3"


def cf(v):
    """float -> C float literal (NAN for missing)."""
    if v is None or (isinstance(v, float) and np.isnan(v)) or pd.isna(v):
        return "NAN"
    return f"{float(np.float32(v))!r}f"


def pick_rows(df, p, thr, rng):
    """8 row indices: 2 high, 2 near threshold, 2 low, 2 with missing inputs (one alert-side if possible)."""
    full = df[["do", "sal", "chl_climatology"]].notna().all(axis=1).values
    miss = ~full
    out = []

    def take(mask, k):
        idx = np.flatnonzero(mask)
        idx = [i for i in idx if i not in out]
        out.extend(rng.choice(idx, size=min(k, len(idx)), replace=False).tolist())

    take(full & (p > 0.85), 2)
    take(full & (p > thr - 0.06) & (p < thr + 0.06), 2)
    take(full & (p < 0.05), 2)
    take(miss & df["do"].isna().values & df["sal"].isna().values & (p >= thr), 1)
    take(miss & df["chl_climatology"].isna().values & (p < thr), 1)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fork", default=DEFAULT_FORK)
    a = ap.parse_args()
    pack = joblib.load(os.path.join(a.fork, "release", "narragansett_bloom_model_v2.joblib"))
    feats, med, thr = pack["features"], pack["medians"], pack["threshold"]
    df = pd.read_csv(os.path.join(a.fork, "data", "narragansett_daily_features.csv"), parse_dates=["date"])

    # ---- 1. model vectors
    X = df[feats].astype(float)
    p_all = pack["model"].predict_proba(X.fillna(pd.Series(med)).values)[:, 1]
    rng = np.random.default_rng(20261005)
    rows = pick_rows(df, p_all, thr, rng)
    sel = df.iloc[rows]
    Xs = sel[feats].astype(float)
    p = pack["model"].predict_proba(Xs.fillna(pd.Series(med)).values)[:, 1]   # same call as export_c_model.py

    # ---- 2. feature-engine history: 29 consecutive rows of one station, clim present on the checked rows
    st = df[df.station == HIST_STATION].reset_index(drop=True)
    ok = st["chl_climatology"].notna() & st["sal"].notna()
    # latest summer window whose checked rows all have salinity and a climatology
    end = next(e for e in range(len(st) - 1, N_HIST, -1)
               if ok.iloc[e - N_HIST_CHECK + 1: e + 1].all() and st["date"].iloc[e].month in (7, 8))
    seg = st.iloc[end - N_HIST + 1: end + 1]

    L = []
    L.append("/* test_vectors.h -- GENERATED by hardware/buoy_esp32/make_test_vectors.py. Do not edit.")
    L.append(f"   Source: {os.path.basename(a.fork)}/data/narragansett_daily_features.csv and")
    L.append("   release/narragansett_bloom_model_v2.joblib. TV_P = Python predict_proba with NaN filled by")
    L.append("   pack['medians'], exactly as src/deploy/export_c_model.py checks the C model. */")
    L.append("#ifndef TEST_VECTORS_H\n#define TEST_VECTORS_H\n#include <math.h>\n")
    L.append(f"#define TV_N {len(rows)}")
    L.append("static const char *const TV_LABEL[TV_N] = {")
    for (_, r), pp in zip(sel.iterrows(), p):
        L.append(f'  "{r.station} {r.date:%Y-%m-%d}",')
    L.append("};")
    L.append("static const float TV_X[TV_N][BLOOM_NF] = {")
    for _, r in Xs.iterrows():
        L.append("  {" + ", ".join(cf(v) for v in r.values) + "},")
    L.append("};")
    L.append("static const double TV_P[TV_N] = {")
    L.append("  " + ", ".join(f"{v:.9f}" for v in p) + ",")
    L.append("};\n")

    L.append(f"/* feature-engine check: {N_HIST} consecutive {HIST_STATION} rows "
             f"{seg.date.iloc[0]:%Y-%m-%d}..{seg.date.iloc[-1]:%Y-%m-%d};")
    L.append(f"   HT_EXPECT = the fork's precomputed features for the last {N_HIST_CHECK} rows. */")
    L.append(f"#define HT_N {N_HIST}\n#define HT_CHECK {N_HIST_CHECK}")
    L.append("static const long HT_DATE[HT_N] = {")
    L.append("  " + ", ".join(f"{d:%Y%m%d}" for d in seg.date) + ",")
    L.append("};")
    L.append("/* chl, temp, sal, do, chl_climatology (fed as a per-day override) */")
    L.append("static const float HT_ROW[HT_N][5] = {")
    for _, r in seg.iterrows():
        L.append("  {" + ", ".join(cf(r[c]) for c in ("chl", "temp", "sal", "do", "chl_climatology")) + "},")
    L.append("};")
    L.append("static const float HT_EXPECT[HT_CHECK][BLOOM_NF] = {")
    for _, r in seg.iloc[-N_HIST_CHECK:][feats].astype(float).iterrows():
        L.append("  {" + ", ".join(cf(v) for v in r.values) + "},")
    L.append("};\n#endif")

    out = os.path.join(HERE, "test_vectors.h")
    with open(out, "w", newline="\n") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"wrote {out}")
    for (_, r), pp in zip(sel.iterrows(), p):
        nm = int(r[feats].isna().sum())
        print(f"  {r.station:6s} {r.date:%Y-%m-%d}  p={pp:.4f}  {'ALERT' if pp >= thr else 'idle '}  missing={nm}")
    print(f"  history: {HIST_STATION} {seg.date.iloc[0]:%Y-%m-%d}..{seg.date.iloc[-1]:%Y-%m-%d}")


if __name__ == "__main__":
    main()
