"""
lis_water_recipe.py -- tank water matched to real Long Island Sound conditions
=============================================================================
Averages CT DEEP's own measurements (surface, 2014-2025; silicate from the UConn/DEEP nutrient
file, through 2024) into a baseline per region and season, then turns the western Sound numbers
into a tank recipe (notes/mitigation/WATER_RECIPE.md):

    warm-up water  = nutrients at the post-spring-bloom low (Mar-Apr median)
    bloom pulse    = winter (Dec-Feb) median minus the warm-up level, i.e. the nutrients a real
                     spring bloom draws down

Units as DEEP reports them: NOx as mg/L N, DIP as mg/L P, SiO2 as mg/L SiO2 (the SiO2 basis is
inferred: as Si the winter values would be ~80-100 uM, far above typical Sound silicate; confirm
with DEEP). Medians, so a few extreme days don't skew the baseline.

Outputs
    data/lab/lis_baseline.csv        median (and IQR) per region x season
    data/lab/lis_water_recipe.csv    stock-solution volumes per 10 L tank, western Sound
    notes/mitigation/LIS_WATER_STATS.md   the baseline table (median and IQR), all regions

Run from repo root:  python src/lab/lis_water_recipe.py
"""
import os

import pandas as pd

S1 = "data/hab_features_tidal_S1.csv"
NUTS = "data/uconn_nutrients_wide.csv"
OUT_DIR = "data/lab"
YEAR_FROM = 2014
REGIONS = ([-74.0, -73.2, -72.6, -71.0], ["West", "Central", "East"])
SEASONS = {12: "Dec-Feb", 1: "Dec-Feb", 2: "Dec-Feb", 3: "Mar-Apr", 4: "Mar-Apr",
           6: "Jun-Aug", 7: "Jun-Aug", 8: "Jun-Aug"}
COLS = {"sea_water_temperature": "temp_c", "sea_water_salinity": "salinity", "pH": "ph",
        "oxygen_concentration_in_sea_water": "do_mg_l", "Corrected_Chlorophyll": "chl_ug_l",
        "NOX-LC": "nox_n_mg_l", "NH#-LC": "nh4_n_mg_l", "DIP": "po4_p_mg_l", "sio2_uconn": "sio2_mg_l"}
TANK_L = 10.0
# (column, salt, grams of element-or-SiO2 per gram of salt, stock g per 100 mL)
STOCKS = [("nox_n_mg_l", "NaNO3", 14.007 / 84.99, 0.590),
          ("po4_p_mg_l", "NaH2PO4.H2O", 30.974 / 137.99, 0.138),
          ("sio2_mg_l", "Na2SiO3.9H2O", 60.08 / 284.2, 2.02)]
MOLAR = {"nox_n_mg_l": 14.007, "po4_p_mg_l": 30.974, "sio2_mg_l": 60.08}
STATS_MD = "notes/mitigation/LIS_WATER_STATS.md"
LABELS = [("temp_c", "Temperature (°C)", 1), ("salinity", "Salinity", 1), ("ph", "pH", 2),
          ("do_mg_l", "Dissolved oxygen (mg/L)", 1), ("chl_ug_l", "Chlorophyll, lab (µg/L)", 1),
          ("nox_n_mg_l", "Nitrate + nitrite (mg/L N)", 3), ("nh4_n_mg_l", "Ammonium (mg/L N)", 3),
          ("po4_p_mg_l", "Phosphate (mg/L P)", 3), ("sio2_mg_l", "Silicate (mg/L SiO₂)", 2)]
REGION_NAMES = {"West": "West (the Narrows to Bridgeport, west of 73.2°W)",
                "Central": "Central (Bridgeport to Clinton, 73.2-72.6°W)",
                "East": "East (Clinton to the Race, east of 72.6°W)"}


def baseline():
    s = pd.read_csv(S1, usecols=["station_name", "date", "longitude_x"] + [c for c in COLS if c != "sio2_uconn"])
    s["day"] = pd.to_datetime(s.date).dt.tz_localize(None).dt.normalize()
    u = pd.read_csv(NUTS, usecols=["station_name", "date", "sio2_uconn"])
    u["day"] = pd.to_datetime(u.date).dt.tz_localize(None).dt.normalize()
    m = s.merge(u.drop(columns="date"), on=["station_name", "day"], how="left").rename(columns=COLS)
    m["region"] = pd.cut(m.longitude_x, REGIONS[0], labels=REGIONS[1])
    m["season"] = m.day.dt.month.map(SEASONS)
    m = m[(m.day.dt.year >= YEAR_FROM) & m.season.notna()]
    g = m.groupby(["region", "season"], observed=True)[list(COLS.values())]
    out = g.median().add_suffix("_median")
    for q in (0.25, 0.75):
        out = out.join(g.quantile(q).add_suffix(f"_q{int(q * 100)}"))
    out["n_visits"] = g.size()
    return out.reset_index()


def recipe(base, region="West"):
    b = base[base.region == region].set_index("season")
    rows = []
    for col, salt, frac, stock_g in STOCKS:
        warm = b.loc["Mar-Apr", f"{col}_median"]
        pulse = b.loc["Dec-Feb", f"{col}_median"] - warm
        stock_mg_per_ml = stock_g * 1000 / 100
        for phase, conc in (("warm-up", warm), ("bloom pulse", pulse)):
            salt_mg = conc * TANK_L / frac
            rows.append(dict(region=region, phase=phase, nutrient=col, target_mg_l=round(conc, 4),
                             target_um=round(conc / MOLAR[col] * 1000, 2), salt=salt,
                             salt_mg_per_tank=round(salt_mg, 2),
                             stock=f"{stock_g:g} g {salt} in 100 mL",
                             stock_ml_per_tank=round(salt_mg / stock_mg_per_ml, 2)))
    return pd.DataFrame(rows)


def write_stats_md(base):
    seasons = ["Dec-Feb", "Mar-Apr", "Jun-Aug"]
    lines = ["# Long Island Sound water statistics (CT DEEP, surface, 2014-2025)", "",
             "Generated by `src/lab/lis_water_recipe.py`; re-run it to update. Each cell is the **median** "
             "with the **typical range** (25th-75th percentile) underneath it. Silicate is through 2024.",
             "Chlorophyll is DEEP's lab-corrected value. Units are as DEEP reports them. The silicate "
             "unit (SiO₂) is inferred; see `WATER_RECIPE.md`.",
             "Use it to set tank water (`WATER_RECIPE.md`) and to check a real Sound sample: a normal "
             "sample for the month should fall inside the typical range.", ""]
    for region in REGION_NAMES:
        b = base[base.region == region].set_index("season")
        lines += [f"## {REGION_NAMES[region]}", "",
                  "| | " + " | ".join(f"{se} (n = {int(b.loc[se, 'n_visits'])})" for se in seasons) + " |",
                  "|---|" + "---|" * len(seasons)]
        for col, label, dp in LABELS:
            cells = []
            for se in seasons:
                med, lo, hi = (b.loc[se, f"{col}_{k}"] for k in ("median", "q25", "q75"))
                cells.append("n/a" if pd.isna(med) else f"**{med:.{dp}f}**<br>{lo:.{dp}f}-{hi:.{dp}f}")
            lines.append(f"| {label} | " + " | ".join(cells) + " |")
        lines.append("")
    lines += ["## Notes",
              "- **Winter to spring drawdown:** nitrate and silicate build up in winter, and the spring diatom "
              "bloom uses up about 90% of them by March-April. The tank bloom pulse copies that drop "
              "(`WATER_RECIPE.md`).",
              "- **Summer:** warmer water, lower pH and lower dissolved oxygen, lowest in the West (the "
              "hypoxia region). Surface values are shown; bottom-water oxygen is lower still.",
              "- **Micromolar conversions:** N mg/L × 71.4, P mg/L × 32.3, SiO₂ mg/L × 16.6.", ""]
    with open(STATS_MD, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    base = baseline()
    base.to_csv(os.path.join(OUT_DIR, "lis_baseline.csv"), index=False)
    rec = recipe(base)
    rec.to_csv(os.path.join(OUT_DIR, "lis_water_recipe.csv"), index=False)
    write_stats_md(base)
    show = ["region", "season", "n_visits"] + [f"{c}_median" for c in COLS.values()]
    print(base[show].round(3).to_string(index=False))
    print()
    print(rec.to_string(index=False))


if __name__ == "__main__":
    main()
